name: chromatic
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
        working-directory: to-do-react
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
